defmodule AshHateoas.Document.Info do
  @moduledoc """
  Introspection for the `document` section.

  The arity-1 reader `document_aggregate_root?/1` is generated by
  `Spark.InfoGenerator`; `aggregate_root?/1` below wraps it so callers get a
  bare boolean whether or not the extension is present at all.
  """

  use Spark.InfoGenerator,
    extension: AshHateoas.Document,
    sections: [:document]

  @doc """
  Whether this resource is the aggregate root — the thing a client authors,
  validates and saves as one document.

  Returns `false` for a resource that does not carry `AshHateoas.Document`, so
  a caller never has to check for the extension first.

  Accepts a resource module or a DSL state, so a transformer can ask before the
  module exists.
  """
  @spec aggregate_root?(Ash.Resource.t() | map()) :: boolean()
  def aggregate_root?(resource_or_dsl) do
    # `Spark.InfoGenerator` returns the bare value for an option with a non-nil
    # default, not an `{:ok, _}` tuple. The rescue covers a resource without
    # the extension, where the section does not exist.
    document_aggregate_root?(resource_or_dsl) == true
  rescue
    _ -> false
  end
end
