defmodule AshHateoas.Test.AuthUser do
  @moduledoc """
  A resource carrying AshAuthentication, so route derivation can prove it skips
  the actions AshAuthentication owns.

  Two kinds of action live here and must be told apart:

    * generated by AshAuthentication — `:sign_in_with_password`,
      `:register_with_password`, `:get_by_subject`. None get a derived route.
    * declared by this resource — `:read`, `:set_role`. Ordinary endpoints, and
      derived as usual.

  Carrying the extension is what must not matter. The rule keys on which
  actions AshAuthentication generated, read from its own introspection, never
  on action names or on the resource itself.
  """

  use Ash.Resource,
    domain: AshHateoas.Test.Domain,
    data_layer: Ash.DataLayer.Ets,
    authorizers: [Ash.Policy.Authorizer],
    extensions: [AshAuthentication, AshHateoas.Resource]

  ets do
    private? true
  end

  hateoas do
    type "auth_user"
  end

  authentication do
    tokens do
      enabled? true
      token_resource AshHateoas.Test.AuthToken
      signing_secret fn _, _ -> {:ok, "test-only-secret-not-used-in-anger"} end
      store_all_tokens? true
    end

    session_identifier :jti

    strategies do
      password :password do
        identity_field :email
        hashed_password_field :hashed_password
        sign_in_tokens_enabled? true
      end
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :email, :ci_string, public?: true, allow_nil?: false
    attribute :hashed_password, :string, allow_nil?: false, sensitive?: true

    attribute :role, :atom,
      public?: true,
      allow_nil?: false,
      default: :member,
      constraints: [one_of: [:member, :admin]]
  end

  identities do
    identity :unique_email, [:email], pre_check_with: AshHateoas.Test.Domain
  end

  actions do
    defaults [:read]

    update :set_role do
      accept [:role]
    end
  end

  policies do
    bypass AshAuthentication.Checks.AshAuthenticationInteraction do
      authorize_if always()
    end

    policy always() do
      authorize_if always()
    end
  end
end
