defmodule AshHateoas.LuaScript.Citations do
  @moduledoc """
  What a script's citations say about a record that is about to be removed.

  A citation is a real foreign key — one nullable `belongs_to` per bind on the
  generated citation resource — so Postgres *can* answer "is this record cited?"
  What it cannot do is answer it **well**: `ON DELETE CASCADE` destroys the
  citation and with it the formula's meaning, `SET NULL` leaves a row naming
  nothing, and `RESTRICT` refuses without saying what to do about it.

  So the reference is declared `:nothing` and these two functions stand in its
  place, for the two things a domain might reasonably want:

    * `cited_by/2` — how many scripts cite this record, for an action that
      should **refuse** while any do.
    * `mark_removed/3` — clear the foreign key, keep the name with a suffix, and
      rewrite the source to match, for an action that should let the record go
      and leave the scripts **visibly broken** rather than silently changed.

  ## Why marking is not deleting

  Removing the citation would take the rest of the script with it — every other
  operand the author wrote, because one thing they referenced went away. Leaving
  the source alone and clearing only the row would be worse: the two are checked
  against each other on every write, so the script would refuse its own next
  update for a reason nothing in it explains.

  Marking keeps both halves saying the same thing, keeps the script readable,
  and makes it unmistakably broken at exactly the spot where the record was.

  ## Which action gets which is the domain's call

  This module does neither by itself. A domain with one destroy door may want to
  refuse; one with two — a guarded `destroy` and an unguarded one — wants both,
  and which is which is a statement about that domain rather than about scripts.
  So each is a function a change module calls, not a change module itself.
  """

  # `filter_input/2` rather than `filter/2`: the column is chosen at run time
  # from the bind name, and `filter/2` is a macro that wants a literal field.
  alias AshHateoas.LuaScript.Info

  @default_suffix " (removed)"

  @doc """
  The citation resource a script resource's citations live in, or `nil`.

  Generated by `AshHateoas.LuaScript.Transformers.DeriveCitations`, so this is
  where a caller asks for it rather than concatenating the name themselves.
  """
  @spec citation_resource(Ash.Resource.t()) :: Ash.Resource.t() | nil
  def citation_resource(script_resource) do
    if Info.script?(script_resource) do
      module = Module.concat(script_resource, Citation)
      if Ash.Resource.Info.resource?(module), do: module
    end
  end

  @doc """
  How many of `script_resource`'s citations name `record`.

  `bind` is the declared bind name — the Lua subscript — which is what picks the
  foreign key column, so a record is only found by citations that meant *its*
  kind. Two records of different binds sharing an id would not be confused, and
  neither would two binds pointing at one resource.
  """
  @spec cited_by(Ash.Resource.t(), atom(), term()) :: non_neg_integer()
  def cited_by(script_resource, bind, id) do
    case citation_resource(script_resource) do
      nil ->
        0

      citation ->
        citation
        |> Ash.Query.filter_input(%{:"#{bind}_id" => id})
        |> Ash.read!(authorize?: false)
        |> length()
    end
  end

  @doc """
  Marks every citation of `id` as removed, in the rows *and* in the source.

  Each matching citation loses its foreign key and keeps its name with `suffix`
  appended; the script's own source has that subscript rewritten to match, so
  the two still agree:

      author["Ada"] * 2          before
      author["Ada (removed)"] * 2    after

  `opts`:

    * `:suffix` — what to append (default `#{inspect(@default_suffix)}`)
    * `:update` — the action to write the rewritten source with, on the script
      resource. Defaults to `:update`; a domain whose ordinary update refuses a
      dangling citation needs a door that does not.

  Returns the number of citations marked.
  """
  @spec mark_removed(Ash.Resource.t(), atom(), term(), keyword()) :: non_neg_integer()
  def mark_removed(script_resource, bind, id, opts \\ []) do
    suffix = Keyword.get(opts, :suffix, @default_suffix)
    update = Keyword.get(opts, :update, :update)
    script = Info.script(script_resource)

    case citation_resource(script_resource) do
      nil ->
        0

      citation_resource ->
        citation_resource
        |> Ash.Query.filter_input(%{:"#{bind}_id" => id})
        |> Ash.Query.load(:script)
        |> Ash.read!(authorize?: false)
        |> Enum.map(&mark(&1, bind, suffix, script, update))
        |> length()
    end
  end

  defp mark(citation, bind, suffix, script, update) do
    marked = "#{citation.name}#{suffix}"

    citation
    |> Ash.Changeset.for_update(:update, %{:name => marked, :"#{bind}_id" => nil})
    |> Ash.update!(authorize?: false)

    rewrite(citation, bind, marked, script, update)
  end

  # The subscript is rewritten by its exact spelling — `author["Ada"]` — rather
  # than by replacing the name wherever it appears, so a name that also occurs
  # inside a string literal is left alone.
  #
  # **`%Ash.NotLoaded{}` is matched explicitly rather than left to a catch-all.**
  # It is a struct, so a `%{script: %{}}` pattern accepts it: the clause matched,
  # `Map.get` returned nil, and the rewrite silently did nothing while the
  # citation row was already cleared — leaving the two halves disagreeing, which
  # is exactly the state this function exists to prevent. Measured, not
  # reasoned about: the row was right and the source was untouched.
  defp rewrite(%{script: %Ash.NotLoaded{}}, _bind, _marked, _script, _update) do
    raise ArgumentError, "the citation's script must be loaded before it can be rewritten"
  end

  defp rewrite(%{script: record, name: name}, bind, marked, script, update)
       when is_struct(record) and is_atom(script) and not is_nil(script) do
    rewritten =
      record
      |> Map.get(script)
      |> String.replace(~s|#{bind}["#{name}"]|, ~s|#{bind}["#{marked}"]|)

    record
    |> Ash.Changeset.for_update(update, %{script => rewritten})
    |> Ash.update!(authorize?: false)
  end

  defp rewrite(_citation, _bind, _marked, _script, _update), do: :ok
end
