defmodule AshHateoas.Hydra.ForeignKeyTest do
  @moduledoc """
  A relationship travels as a link. Its backing foreign key is not API surface.

  `belongs_to :author, Person, public?: true` makes Ash generate an
  `author_id` attribute, and that attribute **inherits the relationship's
  `public?`** — so every path reading `public_attributes/1` picks it up and the
  wire publishes Ash's storage mechanism beside the link that already describes
  the same edge. Nobody chose to publish it; it is the default state.

  Two spellings of one fact, and they are not equally usable: `author` is
  followable and resolvable by identity, while `author_id` is a bare uuid a
  client can do nothing with but send back. Worse, it is the one shape the
  **write** path does not take — `AshHateoas.Hydra.LinkInput` resolves
  `{"author": {"@id": …}}`, so an advertised `author_id` tells a client to send
  something that will be refused.

  ## What must survive

  A foreign key the domain declared **in its own right** is a real part of the
  surface and stays. The fixtures carry both cases deliberately:

    * `Comment.document_id` — generated by a public `belongs_to`. Goes.
    * `Document.owner_id` — a hand-declared `:string` with no relationship
      behind it, used by a record-dependent policy. Stays.

  So the rule is read from the **relationship** side — a `belongs_to` that
  defines its own attribute owns that key — never from the `_id` suffix. A
  suffix match would pass this file's positive cases and silently delete
  `owner_id`, which is why the negative case is asserted as loudly as the
  positive one.
  """

  use ExUnit.Case, async: true

  alias AshHateoas.Hydra.ApiDocumentation
  alias AshHateoas.Test.JsonLd

  defp document, do: ApiDocumentation.build([AshHateoas.Test.Domain])

  # Every `hydra:title` the documentation publishes as a readable property of a
  # class, with the class it belongs to. Document-wide rather than by example:
  # the failure mode is one emitter path still spelling the key.
  defp published_properties do
    for class <- List.wrap(document()["hydra:supportedClass"]),
        property <- List.wrap(class["hydra:supportedProperty"]),
        title = property["hydra:title"],
        is_binary(title),
        do: {(class["@id"] || "") |> String.split("#") |> List.last(), title}
  end

  # The keys Ash generated for a public `belongs_to` — the set that must not
  # reach the wire, derived the same way the emitter derives it rather than
  # listed by hand, so a new fixture relationship is covered without an edit.
  defp generated_keys(resource) do
    resource
    |> Ash.Resource.Info.public_relationships()
    |> Enum.filter(&(&1.type == :belongs_to and Map.get(&1, :define_attribute?, true)))
    |> Enum.map(&to_string(&1.source_attribute))
  end

  defp resources do
    AshHateoas.Test.Domain
    |> Ash.Domain.Info.resources()
    |> Enum.filter(&AshHateoas.Resource.Info.extension?/1)
  end

  describe "a relationship's generated key is not published" do
    test "no class publishes a foreign key its own belongs_to generated" do
      leaked =
        for resource <- resources(),
            keys = generated_keys(resource),
            keys != [],
            type = AshHateoas.Resource.Info.type(resource),
            class = type |> to_string() |> Macro.camelize(),
            {^class, title} <- published_properties(),
            title in keys,
            do: {class, title}

      assert leaked == [],
             "these classes publish a relationship's backing key: #{inspect(leaked)}"
    end

    test "the link describing the same edge is published instead" do
      # The negative half is only safe if the positive one holds: removing the
      # key without the link would leave the edge undescribed, which is worse
      # than duplicating it.
      titles = published_properties()

      for resource <- resources(),
          relationship <- Ash.Resource.Info.public_relationships(resource),
          relationship.type == :belongs_to,
          Map.get(relationship, :define_attribute?, true) do
        class = resource |> AshHateoas.Resource.Info.type() |> to_string() |> Macro.camelize()

        assert {class, to_string(relationship.name)} in titles,
               "#{class} describes neither #{relationship.name} nor its key"
      end
    end
  end

  describe "an attribute the domain declared itself survives" do
    test "a foreign-key-shaped attribute with no relationship is still published" do
      # `Document.owner_id` is a plain `:string` a policy reads
      # (`expr(owner_id == ^actor(:id))`). Nothing generated it, so nothing may
      # remove it — and a filter matching the `_id` suffix would.
      assert {"Document", "owner_id"} in published_properties()
      assert {"Secret", "owner_id"} in published_properties()
    end

    test "the fixture really does distinguish the two cases" do
      # Guards the test above rather than the emitter: if `owner_id` ever gains
      # a relationship, it stops being the negative case and this file proves
      # nothing.
      refute "owner_id" in generated_keys(AshHateoas.Test.Document)
      assert "document_id" in generated_keys(AshHateoas.Test.Comment)
    end
  end

  describe "the record node agrees with the documentation" do
    test "a served node carries the link and not the key" do
      {:ok, document} =
        AshHateoas.Test.Document
        |> Ash.Changeset.for_create(:create, %{title: "t"})
        |> Ash.create(authorize?: false)

      {:ok, comment} =
        AshHateoas.Test.Comment
        |> Ash.Changeset.for_create(:create, %{body: "b", document_id: document.id})
        |> Ash.create(authorize?: false)

      node = served_node(AshHateoas.Test.Comment, comment)

      refute Map.has_key?(node, "document_id"),
             "the node publishes the backing key: #{inspect(Map.keys(node))}"

      assert %{"@id" => _} = node["document"]
    end

    test "the key does not survive expansion either" do
      # The standing rule. A key absent from the JSON is absent from the graph,
      # but a key *present* and unbound expands to nothing — so asserting on
      # the JSON alone cannot tell "removed" from "silently dropped", and the
      # two mean opposite things for whether the edge is stated.
      {:ok, document} =
        AshHateoas.Test.Document
        |> Ash.Changeset.for_create(:create, %{title: "t"})
        |> Ash.create(authorize?: false)

      {:ok, comment} =
        AshHateoas.Test.Comment
        |> Ash.Changeset.for_create(:create, %{body: "b", document_id: document.id})
        |> Ash.create(authorize?: false)

      predicates =
        comment
        |> then(&served_node(AshHateoas.Test.Comment, &1))
        |> JsonLd.expand()
        |> List.first()
        |> Kernel.||(%{})
        |> Map.keys()

      refute Enum.any?(predicates, &String.ends_with?(&1, "comment/document_id"))

      assert Enum.any?(predicates, &String.ends_with?(&1, "comment/document")),
             "the edge is stated by neither the link nor the key"
    end
  end

  # The member route as the resource declares it, rather than a path spelled
  # here: a hand-written URL that 404s produces an error node with none of the
  # keys under test, which reads as a pass for every `refute` in this file.
  defp served_node(resource, record) do
    %{route: route} =
      resource
      |> AshHateoas.Resource.Info.routes()
      |> Enum.find(&(&1.type == :get))

    conn =
      Plug.Test.conn(:get, String.replace(route, ":id", to_string(record.id)))
      |> AshHateoas.Hydra.Plug.call(AshHateoas.Hydra.Plug.init(domains: [AshHateoas.Test.Domain]))

    assert conn.status == 200, "expected the member route to serve the record, got #{conn.status}"

    Jason.decode!(conn.resp_body)
  end
end
